/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.rojoherrero.gondor.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import org.rojoherrero.gondor.model.Drug;
import org.rojoherrero.gondor.model.DrugModel;
import org.rojoherrero.gondor.model.DrugSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Drug service. Represents a row in the &quot;GOndorApp_Drug&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link DrugModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DrugImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DrugImpl
 * @see Drug
 * @see DrugModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DrugModelImpl extends BaseModelImpl<Drug> implements DrugModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a drug model instance should use the {@link Drug} interface instead.
	 */
	public static final String TABLE_NAME = "GOndorApp_Drug";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "drugId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "drugName", Types.VARCHAR },
			{ "drugQuantity", Types.DOUBLE },
			{ "drugType", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("drugId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("drugName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("drugQuantity", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("drugType", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table GOndorApp_Drug (uuid_ VARCHAR(75) null,drugId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,drugName VARCHAR(75) null,drugQuantity DOUBLE,drugType VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table GOndorApp_Drug";
	public static final String ORDER_BY_JPQL = " ORDER BY drug.drugId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY GOndorApp_Drug.drugId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(org.rojoherrero.gondor.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.org.rojoherrero.gondor.model.Drug"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(org.rojoherrero.gondor.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.org.rojoherrero.gondor.model.Drug"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(org.rojoherrero.gondor.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.org.rojoherrero.gondor.model.Drug"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long DRUGTYPE_COLUMN_BITMASK = 2L;
	public static final long GROUPID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long DRUGID_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Drug toModel(DrugSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Drug model = new DrugImpl();

		model.setUuid(soapModel.getUuid());
		model.setDrugId(soapModel.getDrugId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setDrugName(soapModel.getDrugName());
		model.setDrugQuantity(soapModel.getDrugQuantity());
		model.setDrugType(soapModel.getDrugType());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Drug> toModels(DrugSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Drug> models = new ArrayList<Drug>(soapModels.length);

		for (DrugSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(org.rojoherrero.gondor.service.util.PropsUtil.get(
				"lock.expiration.time.org.rojoherrero.gondor.model.Drug"));

	public DrugModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _drugId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDrugId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _drugId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Drug.class;
	}

	@Override
	public String getModelClassName() {
		return Drug.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("drugId", getDrugId());
		attributes.put("groupId", getGroupId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("drugName", getDrugName());
		attributes.put("drugQuantity", getDrugQuantity());
		attributes.put("drugType", getDrugType());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long drugId = (Long)attributes.get("drugId");

		if (drugId != null) {
			setDrugId(drugId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String drugName = (String)attributes.get("drugName");

		if (drugName != null) {
			setDrugName(drugName);
		}

		Double drugQuantity = (Double)attributes.get("drugQuantity");

		if (drugQuantity != null) {
			setDrugQuantity(drugQuantity);
		}

		String drugType = (String)attributes.get("drugType");

		if (drugType != null) {
			setDrugType(drugType);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDrugId() {
		return _drugId;
	}

	@Override
	public void setDrugId(long drugId) {
		_drugId = drugId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getDrugName() {
		if (_drugName == null) {
			return StringPool.BLANK;
		}
		else {
			return _drugName;
		}
	}

	@Override
	public void setDrugName(String drugName) {
		_drugName = drugName;
	}

	@JSON
	@Override
	public double getDrugQuantity() {
		return _drugQuantity;
	}

	@Override
	public void setDrugQuantity(double drugQuantity) {
		_drugQuantity = drugQuantity;
	}

	@JSON
	@Override
	public String getDrugType() {
		if (_drugType == null) {
			return StringPool.BLANK;
		}
		else {
			return _drugType;
		}
	}

	@Override
	public void setDrugType(String drugType) {
		_columnBitmask |= DRUGTYPE_COLUMN_BITMASK;

		if (_originalDrugType == null) {
			_originalDrugType = _drugType;
		}

		_drugType = drugType;
	}

	public String getOriginalDrugType() {
		return GetterUtil.getString(_originalDrugType);
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				Drug.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			Drug.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Drug toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Drug)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DrugImpl drugImpl = new DrugImpl();

		drugImpl.setUuid(getUuid());
		drugImpl.setDrugId(getDrugId());
		drugImpl.setGroupId(getGroupId());
		drugImpl.setCompanyId(getCompanyId());
		drugImpl.setUserId(getUserId());
		drugImpl.setUserName(getUserName());
		drugImpl.setCreateDate(getCreateDate());
		drugImpl.setModifiedDate(getModifiedDate());
		drugImpl.setDrugName(getDrugName());
		drugImpl.setDrugQuantity(getDrugQuantity());
		drugImpl.setDrugType(getDrugType());

		drugImpl.resetOriginalValues();

		return drugImpl;
	}

	@Override
	public int compareTo(Drug drug) {
		long primaryKey = drug.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Drug)) {
			return false;
		}

		Drug drug = (Drug)obj;

		long primaryKey = drug.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		DrugModelImpl drugModelImpl = this;

		drugModelImpl._originalUuid = drugModelImpl._uuid;

		drugModelImpl._originalGroupId = drugModelImpl._groupId;

		drugModelImpl._setOriginalGroupId = false;

		drugModelImpl._originalCompanyId = drugModelImpl._companyId;

		drugModelImpl._setOriginalCompanyId = false;

		drugModelImpl._setModifiedDate = false;

		drugModelImpl._originalDrugType = drugModelImpl._drugType;

		drugModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Drug> toCacheModel() {
		DrugCacheModel drugCacheModel = new DrugCacheModel();

		drugCacheModel.uuid = getUuid();

		String uuid = drugCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			drugCacheModel.uuid = null;
		}

		drugCacheModel.drugId = getDrugId();

		drugCacheModel.groupId = getGroupId();

		drugCacheModel.companyId = getCompanyId();

		drugCacheModel.userId = getUserId();

		drugCacheModel.userName = getUserName();

		String userName = drugCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			drugCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			drugCacheModel.createDate = createDate.getTime();
		}
		else {
			drugCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			drugCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			drugCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		drugCacheModel.drugName = getDrugName();

		String drugName = drugCacheModel.drugName;

		if ((drugName != null) && (drugName.length() == 0)) {
			drugCacheModel.drugName = null;
		}

		drugCacheModel.drugQuantity = getDrugQuantity();

		drugCacheModel.drugType = getDrugType();

		String drugType = drugCacheModel.drugType;

		if ((drugType != null) && (drugType.length() == 0)) {
			drugCacheModel.drugType = null;
		}

		return drugCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", drugId=");
		sb.append(getDrugId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", drugName=");
		sb.append(getDrugName());
		sb.append(", drugQuantity=");
		sb.append(getDrugQuantity());
		sb.append(", drugType=");
		sb.append(getDrugType());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("org.rojoherrero.gondor.model.Drug");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>drugId</column-name><column-value><![CDATA[");
		sb.append(getDrugId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>drugName</column-name><column-value><![CDATA[");
		sb.append(getDrugName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>drugQuantity</column-name><column-value><![CDATA[");
		sb.append(getDrugQuantity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>drugType</column-name><column-value><![CDATA[");
		sb.append(getDrugType());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Drug.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Drug.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _drugId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _drugName;
	private double _drugQuantity;
	private String _drugType;
	private String _originalDrugType;
	private long _columnBitmask;
	private Drug _escapedModel;
}