/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.rojoherrero.gondor.pharmacy.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Drug service. Represents a row in the &quot;GondorPharmacy_Drug&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.rojoherrero.gondor.pharmacy.model.impl.DrugModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.rojoherrero.gondor.pharmacy.model.impl.DrugImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Drug
 * @see org.rojoherrero.gondor.pharmacy.model.impl.DrugImpl
 * @see org.rojoherrero.gondor.pharmacy.model.impl.DrugModelImpl
 * @generated
 */
@ProviderType
public interface DrugModel extends BaseModel<Drug>, GroupedModel, ShardedModel,
	StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a drug model instance should use the {@link Drug} interface instead.
	 */

	/**
	 * Returns the primary key of this drug.
	 *
	 * @return the primary key of this drug
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this drug.
	 *
	 * @param primaryKey the primary key of this drug
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this drug.
	 *
	 * @return the uuid of this drug
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this drug.
	 *
	 * @param uuid the uuid of this drug
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the drug ID of this drug.
	 *
	 * @return the drug ID of this drug
	 */
	public long getDrugId();

	/**
	 * Sets the drug ID of this drug.
	 *
	 * @param drugId the drug ID of this drug
	 */
	public void setDrugId(long drugId);

	/**
	 * Returns the group ID of this drug.
	 *
	 * @return the group ID of this drug
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this drug.
	 *
	 * @param groupId the group ID of this drug
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this drug.
	 *
	 * @return the company ID of this drug
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this drug.
	 *
	 * @param companyId the company ID of this drug
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this drug.
	 *
	 * @return the user ID of this drug
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this drug.
	 *
	 * @param userId the user ID of this drug
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this drug.
	 *
	 * @return the user uuid of this drug
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this drug.
	 *
	 * @param userUuid the user uuid of this drug
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this drug.
	 *
	 * @return the user name of this drug
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this drug.
	 *
	 * @param userName the user name of this drug
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this drug.
	 *
	 * @return the create date of this drug
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this drug.
	 *
	 * @param createDate the create date of this drug
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this drug.
	 *
	 * @return the modified date of this drug
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this drug.
	 *
	 * @param modifiedDate the modified date of this drug
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the drug name of this drug.
	 *
	 * @return the drug name of this drug
	 */
	@AutoEscape
	public String getDrugName();

	/**
	 * Sets the drug name of this drug.
	 *
	 * @param drugName the drug name of this drug
	 */
	public void setDrugName(String drugName);

	/**
	 * Returns the drug type of this drug.
	 *
	 * @return the drug type of this drug
	 */
	@AutoEscape
	public String getDrugType();

	/**
	 * Sets the drug type of this drug.
	 *
	 * @param drugType the drug type of this drug
	 */
	public void setDrugType(String drugType);

	/**
	 * Returns the drug quantity of this drug.
	 *
	 * @return the drug quantity of this drug
	 */
	public double getDrugQuantity();

	/**
	 * Sets the drug quantity of this drug.
	 *
	 * @param drugQuantity the drug quantity of this drug
	 */
	public void setDrugQuantity(double drugQuantity);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Drug drug);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Drug> toCacheModel();

	@Override
	public Drug toEscapedModel();

	@Override
	public Drug toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}